name: auto-study

on:
  schedule:
    - cron: "42 0 * * MON"
    # 每周一执行workflow

  workflow_dispatch: # 手动执行workflow

env:
  msg: "qndxx"
  # USER_ID: ${{ secrets.USER_ID }}

jobs:
  study1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"
      - run: yarn
      - run: yarn start ${{ secrets.SESSION_BOT }}
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: release
        uses: marvinpinto/action-automatic-releases@latest
        env:
          TAG_NAME: nightly-tag-${{ steps.date.outputs.date }}
          RELEASE_NAME: nightly-release-${{ steps.date.outputs.date }}
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          tag_name: ${{ steps.date.outputs.date }}
          release_name: ${{ steps.date.outputs.date }}
          automatic_release_tag: ${{ steps.date.outputs.date }}
          title: ${{ steps.date.outputs.date }}
          prerelease: false
          files: |
            output/*
